export const ERRORS = {
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNDEFINED_TOKEN: 'UNDEFINED_TOKEN',
  NO_ACCESS: 'NO_ACCESS',
  INVALID_DATA: 'INVALID_DATA',
  WRONG_LOGIN_PASSWORD: 'WRONG_LOGIN_PASSWORD',
  PASSWORD_DONT_MATCH: 'PASSWORD_DONT_MATCH',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
};

export const NEIGHBORHOOD_ERRORS = {
  NEIGHBORHOOD_NOT_FOUND: 'NEIGHBORHOOD_NOT_FOUND',
  INVITE_CODE_EXPIRED: 'INVITE_CODE_EXPIRED',
  ALREADY_IN_NEIGHBORHOOD: 'ALREADY_IN_NEIGHBORHOOD',
  USER_NOT_IN_NEIGHBORHOOD: 'USER_NOT_IN_NEIGHBORHOOD',
};

export const DEBT_ERRORS = {
  PAYMENT_EXCEEDS_DEBT: 'PAYMENT_EXCEEDS_DEBT',
  WRONG_NEW_DEBT_AMOUNT: 'WRONG_NEW_DEBT_AMOUNT',
};

export const PLAN_ERRORS = {
  NOT_ENOUGH_PARTICIPANTS: 'NOT_ENOUGH_PARTICIPANTS',
  WRONG_PAYMENT_AMOUNT: 'WRONG_PAYMENT_AMOUNT',
  WRONG_NEW_PLAN_AMOUNT: 'WRONG_NEW_PLAN_AMOUNT',
};

export const DUTY_ERRORS = {
  NOT_ENOUGH_PARTICIPANTS: 'NOT_ENOUGH_PARTICIPANTS',
  MARK_ALREADY_EXIST: 'MARK_ALREADY_EXIST',
};
