export const ROUTES = {
  NEIGHBORHOOD: {
    DEFAULT: '/api/neighborhood',
    CREATE: '/create',
    GET_BY_CODE: '/get-by-code',
    JOIN_BY_CODE: '/join-by-code',
    GET_USER_NEIGHBORHOODS: '/get-user-neighborhoods',
    GET_CURRENT: '/get-current',
    EDIT: '/edit',
    SET_FAVORITE: '/set-favorite',
    REMOVE_FAVORITE: '/remove-favorite',
    REMOVE_USER: '/remove-user',
    GENERATE_INVITE_CODE: '/generate-invite-code',
    REMOVE_INVITE_CODE: '/remove-invite-code',
    DELETE: '/delete',
    LEAVE_NEIGHBORHOOD: '/leave',
  },
  USER: {
    DEFAULT: '/api/user',
    EDIT: '/edit-profile',
    CHANGE_PASSWORD: '/change-password',
  },
  AUTH: {
    DEFAULT: '/api/auth',
    LOGIN: '/login',
    REGISTER: '/register',
    LOGOUT: '/logout',
    REFRESH: '/refresh',
    EDIT: '/edit-profile',
  },
  DEBT: {
    DEFAULT: '/api/debt',
    CREATE: '/create',
    EDIT: '/edit',
    GET_USER_DEBTS: '/get',
    GET_USER_DEBTS_BY_ID: '/get-by-id',
    DELETE: '/delete',
    ADD_PAYMENT: '/add-payment',
    CLOSE_DEBT: '/close-debt',
  },
  DUTY: {
    DEFAULT: '/api/duty',
    GET_USER_DUTIES_BY_ID: '/get-by-id',
    GET_USER_DUTIES: '/get',
    CREATE: '/create',
    EDIT: '/edit',
    DELETE: '/delete',
    ADD_MARK: '/add-mark',
    DELETE_MARK: '/delete-mark',
    ADD_PARTICIPANT: '/add-participant',
    REMOVE_PARTICIPANT: '/remove-participant',
  },
  PLAN: {
    DEFAULT: '/api/plan',
    CREATE: '/create',
    GET_USER_PLANS: '/get',
    GET_USER_PLANS_BY_ID: '/get-by-id',
    EDIT: '/edit',
    CHANGE_TASK_STATUS: '/change-task-status',
    ADD_PAYMENT: '/add-payment',
    CLOSE_PLAN: '/close-plan',
    REOPEN_PLAN: '/reopen-plan',
    DELETE: '/delete',
    ADD_PARTICIPANT: '/add-participant',
    REMOVE_PARTICIPANT: '/remove-participant',
  },
  CHAT: {
    DEFAULT: '/api/chat',
    UPDATE_VIEWED_MESSAGES: '/update-viewed-message',
    LOAD_MORE_MESSAGES: '/load-more-messages',
  },
};
