export const ERRORS = {
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  NO_ACCESS: 'NO_ACCESS',
  INVALID_DATA: 'INVALID_DATA',
  WRONG_LOGIN_PASSWORD: 'WRONG_LOGIN_PASSWORD',
};

export const AUTH_ERRORS = {
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNDEFINED_TOKEN: 'UNDEFINED_TOKEN',
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
};

export const DEFAULT_ERRORS = {
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
};

export const NEIGHBORHOOD_ERRORS = {
  NEIGHBORHOOD_NOT_FOUND: 'NEIGHBORHOOD_NOT_FOUND',
  INVITE_CODE_EXPIRED: 'INVITE_CODE_EXPIRED',
  ALREADY_IN_NEIGHBORHOOD: 'ALREADY_IN_NEIGHBORHOOD',
  NO_ACCESS: 'NO_ACCESS',
};

export const PLAN_ERRORS = {
  NOT_ENOUGH_PARTICIPANTS: 'NOT_ENOUGH_PARTICIPANTS',
};
